apiVersion: v1
kind: Service
metadata:
  name: riggs
  labels:
    run: riggs
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 5050
      protocol: TCP
  selector:
    selector_app: riggs
